"""'BasedeDatos'

Revision ID: 0dc0ef036a83
Revises: 
Create Date: 2025-11-05 00:27:27.229314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dc0ef036a83'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=30), nullable=True),
    sa.Column('correo', sa.VARCHAR(length=50), nullable=True),
    sa.Column('celular', sa.String(length=15), nullable=True),
    sa.Column('tipo_identificacion', sa.String(length=5), nullable=True),
    sa.Column('identificacion', sa.String(length=15), nullable=True),
    sa.Column('contrasena', sa.VARCHAR(length=100), nullable=True),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=True),
    sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('celular'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('identificacion')
    )
    op.create_table('ciudad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('hotel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=False),
    sa.Column('direccion', sa.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auditoria_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=10), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('old_data', sa.JSON(), nullable=True),
    sa.Column('new_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['administrador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_plan_id'), 'auditoria_plan', ['id'], unique=False)
    op.create_table('estadia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habitacion', sa.VARCHAR(length=100), nullable=False),
    sa.Column('numHabitacion', sa.VARCHAR(length=200), nullable=False),
    sa.Column('numDias', sa.VARCHAR(length=200), nullable=False),
    sa.Column('numNoche', sa.VARCHAR(length=200), nullable=False),
    sa.Column('precioDia', sa.VARCHAR(length=200), nullable=False),
    sa.Column('precioNoche', sa.VARCHAR(length=200), nullable=False),
    sa.Column('tipoHabitacion', sa.VARCHAR(length=200), nullable=False),
    sa.Column('id_hotel', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_hotel'], ['hotel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('informe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('id_administrador', sa.Integer(), nullable=True),
    sa.Column('ruta_pdf', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['id_administrador'], ['administrador.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_informe_id'), 'informe', ['id'], unique=False)
    op.create_table('turista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=30), nullable=True),
    sa.Column('correo', sa.VARCHAR(length=50), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('direccion', sa.VARCHAR(length=50), nullable=True),
    sa.Column('tipo_identificacion', sa.String(length=5), nullable=True),
    sa.Column('identificacion', sa.String(length=30), nullable=True),
    sa.Column('contrasena', sa.VARCHAR(length=100), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('acepto_terminos', sa.Boolean(), nullable=True),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=True),
    sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True),
    sa.Column('pin_recuperacion', sa.String(length=6), nullable=True),
    sa.Column('expira_pin', sa.DateTime(), nullable=True),
    sa.Column('token_recuperacion', sa.String(length=255), nullable=True),
    sa.Column('expira_token', sa.DateTime(), nullable=True),
    sa.Column('ciudad_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ciudad_id'], ['ciudad.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('celular'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('identificacion')
    )
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=30), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('descripcion_corta', sa.String(length=100), nullable=True),
    sa.Column('costo_persona', sa.Integer(), nullable=True),
    sa.Column('imagen', sa.VARCHAR(length=255), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('mostrar_en_carrusel', sa.Boolean(), nullable=True),
    sa.Column('id_ciudad', sa.Integer(), nullable=True),
    sa.Column('id_informe', sa.Integer(), nullable=True),
    sa.Column('id_Admin', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_Admin'], ['administrador.id'], ),
    sa.ForeignKeyConstraint(['id_ciudad'], ['ciudad.id'], ),
    sa.ForeignKeyConstraint(['id_informe'], ['informe.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descripcion'),
    sa.UniqueConstraint('descripcion_corta'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tarjeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tipo_tarjeta', sa.VARCHAR(length=50), nullable=False),
    sa.Column('numero', sa.VARCHAR(length=16), nullable=False),
    sa.Column('fecha_vencimiento', sa.VARCHAR(length=200), nullable=False),
    sa.Column('cvv', sa.Integer(), nullable=False),
    sa.Column('turista_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['turista_id'], ['turista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_turista', sa.Integer(), nullable=False),
    sa.Column('id_plan', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_plan'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['id_turista'], ['turista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_reserva', sa.Date(), nullable=True),
    sa.Column('costo_final', sa.Integer(), nullable=True),
    sa.Column('disponibilidad', sa.Boolean(), nullable=True),
    sa.Column('numero_personas', sa.Integer(), nullable=True),
    sa.Column('comprobante_pdf', sa.LargeBinary(), nullable=True),
    sa.Column('id_informe', sa.Integer(), nullable=True),
    sa.Column('id_plan', sa.Integer(), nullable=True),
    sa.Column('id_turista', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_informe'], ['informe.id'], ),
    sa.ForeignKeyConstraint(['id_plan'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['id_turista'], ['turista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ubicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('longitud', sa.VARCHAR(length=30), nullable=True),
    sa.Column('latitud', sa.VARCHAR(length=30), nullable=True),
    sa.Column('id_plan', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_plan'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona_reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('tipo_identificacion', sa.String(length=5), nullable=False),
    sa.Column('identificacion', sa.String(length=15), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('id_reserva', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_reserva'], ['reserva.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_reserva_id'), 'persona_reserva', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_persona_reserva_id'), table_name='persona_reserva')
    op.drop_table('persona_reserva')
    op.drop_table('ubicacion')
    op.drop_table('reserva')
    op.drop_table('favorito')
    op.drop_table('tarjeta')
    op.drop_table('plan')
    op.drop_table('turista')
    op.drop_index(op.f('ix_informe_id'), table_name='informe')
    op.drop_table('informe')
    op.drop_table('estadia')
    op.drop_index(op.f('ix_auditoria_plan_id'), table_name='auditoria_plan')
    op.drop_table('auditoria_plan')
    op.drop_table('hotel')
    op.drop_table('ciudad')
    op.drop_table('administrador')
    # ### end Alembic commands ###
