"""'relacion5'

Revision ID: 3b5e959c0b30
Revises: 291f144e2188
Create Date: 2025-11-05 00:31:03.063694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3b5e959c0b30'
down_revision: Union[str, None] = '291f144e2188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('informe', sa.Column('ruta_pdf', sa.String(length=500), nullable=False))
    op.alter_column('informe', 'nombre',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('informe', 'fecha_creacion',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)
    op.create_index(op.f('ix_informe_id'), 'informe', ['id'], unique=False)
    op.add_column('plan', sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('plan', sa.Column('mostrar_en_carrusel', sa.Boolean(), nullable=True))
    op.add_column('turista', sa.Column('estado', sa.Boolean(), nullable=True))
    op.add_column('turista', sa.Column('fecha_registro', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turista', 'fecha_registro')
    op.drop_column('turista', 'estado')
    op.drop_column('plan', 'mostrar_en_carrusel')
    op.drop_column('plan', 'fecha_creacion')
    op.drop_index(op.f('ix_informe_id'), table_name='informe')
    op.alter_column('informe', 'fecha_creacion',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('informe', 'nombre',
               existing_type=sa.VARCHAR(length=100),
               type_=mysql.VARCHAR(length=30),
               nullable=True)
    op.drop_column('informe', 'ruta_pdf')
    # ### end Alembic commands ###
