"""'Cambia_disponibilidad_a_estado_num1'

Revision ID: 77c62fda55d7
Revises: 8e9dbb09dc3e
Create Date: 2025-11-09 22:08:58.120087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77c62fda55d7'
down_revision: Union[str, None] = '8e9dbb09dc3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
