"""'Cambia_disponibilidad_a_estado_num'

Revision ID: 87ff87963ad6
Revises: d5c81c57559e
Create Date: 2025-11-09 21:39:38.522881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '87ff87963ad6'
down_revision: Union[str, None] = 'd5c81c57559e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reserva', sa.Column('estado', sa.Enum('CONFIRMADA', 'CANCELADA', 'FINALIZADA', name='estadoreserva'), nullable=False))
    op.drop_column('reserva', 'disponibilidad')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reserva', sa.Column('disponibilidad', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('reserva', 'estado')
    # ### end Alembic commands ###
