"""'Cambio_Campo_a_Disponibilidad_tabla_reservas'

Revision ID: 8e9dbb09dc3e
Revises: 87ff87963ad6
Create Date: 2025-11-09 22:01:28.998976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8e9dbb09dc3e'
down_revision: Union[str, None] = '87ff87963ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reserva', sa.Column('disponibilidad', sa.Enum('CONFIRMADA', 'CANCELADA', 'FINALIZADA', name='estadoreserva'), nullable=False))
    op.drop_column('reserva', 'estado')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reserva', sa.Column('estado', mysql.ENUM('CONFIRMADA', 'CANCELADA', 'FINALIZADA'), nullable=False))
    op.drop_column('reserva', 'disponibilidad')
    # ### end Alembic commands ###
